// Tableau exhaustif des pays du monde avec URL Wikimedia (SVG)
// Format : { url: ..., pays: ... }
export const drapeauxMonde = [
  { url: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Afghanistan.svg", pays: "Afghanistan" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Albania.svg", pays: "Albanie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Flag_of_Algeria.svg", pays: "Algérie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Andorra.svg", pays: "Andorre" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Angola.svg", pays: "Angola" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Antigua_and_Barbuda.svg", pays: "Antigua-et-Barbuda" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Argentina.svg", pays: "Argentine" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Armenia.svg", pays: "Arménie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Australia.svg", pays: "Australie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg", pays: "Autriche" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg", pays: "Azerbaïdjan" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Bahamas.svg", pays: "Bahamas" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/9/91/Flag_of_Bahrain.svg", pays: "Bahreïn" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Bangladesh.svg", pays: "Bangladesh" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Flag_of_Barbados.svg", pays: "Barbade" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Belarus.svg", pays: "Biélorussie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg", pays: "Belgique" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Belize.svg", pays: "Belize" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Benin.svg", pays: "Bénin" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Bhutan.svg", pays: "Bhoutan" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Bolivia.svg", pays: "Bolivie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Bosnia_and_Herzegovina.svg", pays: "Bosnie-Herzégovine" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Botswana.svg", pays: "Botswana" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Brazil.svg", pays: "Brésil" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Brunei.svg", pays: "Brunei" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Bulgaria.svg", pays: "Bulgarie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Burkina_Faso.svg", pays: "Burkina Faso" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/02/Flag_of_Burundi.svg", pays: "Burundi" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Cambodia.svg", pays: "Cambodge" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Cameroon.svg", pays: "Cameroun" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Canada.svg", pays: "Canada" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Cape_Verde.svg", pays: "Cap-Vert" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Central_African_Republic.svg", pays: "République centrafricaine" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Chad.svg", pays: "Tchad" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Chile.svg", pays: "Chili" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_China.svg", pays: "Chine" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Flag_of_Colombia.svg", pays: "Colombie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Comoros.svg", pays: "Comores" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_the_Democratic_Republic_of_the_Congo.svg", pays: "République démocratique du Congo" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Republic_of_the_Congo.svg", pays: "République du Congo" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Costa_Rica.svg", pays: "Costa Rica" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_C%C3%B4te_d%27Ivoire.svg", pays: "Côte d'Ivoire" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/5/51/Flag_of_Croatia.svg", pays: "Croatie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cuba.svg", pays: "Cuba" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg", pays: "Chypre" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_the_Czech_Republic.svg", pays: "Tchéquie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Flag_of_Denmark.svg", pays: "Danemark" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Djibouti.svg", pays: "Djibouti" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Dominica.svg", pays: "Dominique" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg", pays: "République dominicaine" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_East_Timor.svg", pays: "Timor oriental" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Ecuador.svg", pays: "Équateur" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Egypt.svg", pays: "Égypte" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_El_Salvador.svg", pays: "Salvador" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Equatorial_Guinea.svg", pays: "Guinée équatoriale" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Flag_of_Eritrea.svg", pays: "Érythrée" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Estonia.svg", pays: "Estonie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Eswatini.svg", pays: "Eswatini" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Ethiopia.svg", pays: "Éthiopie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Fiji.svg", pays: "Fidji" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Finland.svg", pays: "Finlande" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_France.svg", pays: "France" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Gabon.svg", pays: "Gabon" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_The_Gambia.svg", pays: "Gambie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Georgia.svg", pays: "Géorgie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg", pays: "Allemagne" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Ghana.svg", pays: "Ghana" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Greece.svg", pays: "Grèce" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Grenada.svg", pays: "Grenade" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Guatemala.svg", pays: "Guatemala" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Guinea.svg", pays: "Guinée" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Guinea-Bissau.svg", pays: "Guinée-Bissau" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Guyana.svg", pays: "Guyana" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Haiti.svg", pays: "Haïti" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Honduras.svg", pays: "Honduras" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Hungary.svg", pays: "Hongrie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Iceland.svg", pays: "Islande" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_India.svg", pays: "Inde" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Indonesia.svg", pays: "Indonésie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Iran.svg", pays: "Iran" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Iraq.svg", pays: "Irak" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Ireland.svg", pays: "Irlande" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Israel.svg", pays: "Israël" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Italy.svg", pays: "Italie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Jamaica.svg", pays: "Jamaïque" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Japan.svg", pays: "Japon" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Jordan.svg", pays: "Jordanie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Kazakhstan.svg", pays: "Kazakhstan" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Kenya.svg", pays: "Kenya" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Kiribati.svg", pays: "Kiribati" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_North_Korea.svg", pays: "Corée du Nord" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_South_Korea.svg", pays: "Corée du Sud" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Kuwait.svg", pays: "Koweït" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Kyrgyzstan.svg", pays: "Kirghizistan" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Laos.svg", pays: "Laos" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Latvia.svg", pays: "Lettonie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Lebanon.svg", pays: "Liban" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Lesotho.svg", pays: "Lesotho" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Liberia.svg", pays: "Libéria" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Libya.svg", pays: "Libye" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Liechtenstein.svg", pays: "Liechtenstein" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Lithuania.svg", pays: "Lituanie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Luxembourg.svg", pays: "Luxembourg" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Madagascar.svg", pays: "Madagascar" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Malawi.svg", pays: "Malawi" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Malaysia.svg", pays: "Malaisie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Maldives.svg", pays: "Maldives" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Mali.svg", pays: "Mali" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Malta.svg", pays: "Malte" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Marshall_Islands.svg", pays: "Îles Marshall" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Mauritania.svg", pays: "Mauritanie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Mauritius.svg", pays: "Maurice" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Mexico.svg", pays: "Mexique" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Micronesia.svg", pays: "Micronésie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Moldova.svg", pays: "Moldavie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Monaco.svg", pays: "Monaco" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Mongolia.svg", pays: "Mongolie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Montenegro.svg", pays: "Monténégro" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Morocco.svg", pays: "Maroc" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Mozambique.svg", pays: "Mozambique" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Myanmar.svg", pays: "Myanmar" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Namibia.svg", pays: "Namibie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Nauru.svg", pays: "Nauru" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Nepal.svg", pays: "Népal" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Netherlands.svg", pays: "Pays-Bas" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_New_Zealand.svg", pays: "Nouvelle-Zélande" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Nicaragua.svg", pays: "Nicaragua" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Niger.svg", pays: "Niger" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Nigeria.svg", pays: "Nigéria" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_North_Macedonia.svg", pays: "Macédoine du Nord" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Norway.svg", pays: "Norvège" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Oman.svg", pays: "Oman" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Pakistan.svg", pays: "Pakistan" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Palau.svg", pays: "Palaos" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Palestine.svg", pays: "Palestine" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Panama.svg", pays: "Panama" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Papua_New_Guinea.svg", pays: "Papouasie-Nouvelle-Guinée" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Paraguay.svg", pays: "Paraguay" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Peru.svg", pays: "Pérou" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Philippines.svg", pays: "Philippines" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Poland.svg", pays: "Pologne" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg", pays: "Portugal" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Qatar.svg", pays: "Qatar" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Romania.svg", pays: "Roumanie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Russia.svg", pays: "Russie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Rwanda.svg", pays: "Rwanda" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Saint_Kitts_and_Nevis.svg", pays: "Saint-Christophe-et-Niévès" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Saint_Lucia.svg", pays: "Sainte-Lucie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Saint_Vincent_and_the_Grenadines.svg", pays: "Saint-Vincent-et-les-Grenadines" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Samoa.svg", pays: "Samoa" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_San_Marino.svg", pays: "Saint-Marin" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Sao_Tome_and_Principe.svg", pays: "Sao Tomé-et-Principe" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Saudi_Arabia.svg", pays: "Arabie saoudite" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Senegal.svg", pays: "Sénégal" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Serbia.svg", pays: "Serbie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Seychelles.svg", pays: "Seychelles" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Sierra_Leone.svg", pays: "Sierra Leone" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Singapore.svg", pays: "Singapour" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Slovakia.svg", pays: "Slovaquie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Slovenia.svg", pays: "Slovénie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Solomon_Islands.svg", pays: "Îles Salomon" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Somalia.svg", pays: "Somalie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_South_Africa.svg", pays: "Afrique du Sud" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_South_Sudan.svg", pays: "Soudan du Sud" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Spain.svg", pays: "Espagne" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Sri_Lanka.svg", pays: "Sri Lanka" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Sudan.svg", pays: "Soudan" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Suriname.svg", pays: "Suriname" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Sweden.svg", pays: "Suède" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Switzerland.svg", pays: "Suisse" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Syria.svg", pays: "Syrie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Taiwan.svg", pays: "Taïwan" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Tajikistan.svg", pays: "Tadjikistan" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Tanzania.svg", pays: "Tanzanie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Thailand.svg", pays: "Thaïlande" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Togo.svg", pays: "Togo" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Tonga.svg", pays: "Tonga" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Trinidad_and_Tobago.svg", pays: "Trinité-et-Tobago" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Tunisia.svg", pays: "Tunisie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Turkey.svg", pays: "Turquie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Turkmenistan.svg", pays: "Turkménistan" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Tuvalu.svg", pays: "Tuvalu" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Uganda.svg", pays: "Ouganda" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Ukraine.svg", pays: "Ukraine" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_United_Arab_Emirates.svg", pays: "Émirats arabes unis" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_the_United_Kingdom.svg", pays: "Royaume-Uni" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_the_United_States.svg", pays: "États-Unis" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Uruguay.svg", pays: "Uruguay" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Uzbekistan.svg", pays: "Ouzbékistan" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Vanuatu.svg", pays: "Vanuatu" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Vatican_City.svg", pays: "Vatican" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Venezuela.svg", pays: "Venezuela" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Vietnam.svg", pays: "Viêt Nam" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Yemen.svg", pays: "Yémen" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Zambia.svg", pays: "Zambie" },
  { url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Zimbabwe.svg", pays: "Zimbabwe" }
];
// Liste tronquée ici pour l'exemple. Le tableau complet sera injecté dans App.jsx.
